### ISSUE TITLE
How Do I Deploy

### ISSUE THREAD

**Issue by Ray-Ping-Miners** [dragon731012/DM-Unbl0cker#11]

**Comment by ghost** [comment]
> 1. Fork this
> 2. Go to render.com and sign up with GitHub
> 3. Click create web service
> 4. Click repo to deploy
> 5. Make build command node
> 6. It will give you your website

when i try to deploy it to render it says "this action is not allowed"
also, i forked it and deployed the bare server to render. I added the new bare server to uv/uv.config.js and am unsure what to do with my fork of this site now.
please respond quick, thanks

**Comment by dragon731012** [comment]
Go to netlify.com or vercel.com and create it, it is now a static unblocker

**Comment by ghost** [comment]
> Go to netlify.com or vercel.com and create it, it is now a static unblocker 

Appreciate it a lot bro

**Comment by dragon731012** [comment]
no problem
