### ISSUE TITLE
links

### ISSUE THREAD

**Issue by Karichain** [dragon731012/DM-Unbl0cker#12]
need links bc i dont have disk

**Comment by dragon731012** [comment]
I’ll give you 1:
https://ixlmathwork.onrender.com/

**Comment by Karichain** [comment]
blcked

**Comment by MrBrodieSkyland** [comment]
link is saying not found

**Comment by narmadikmanokat** [comment]
any github.io links?

**Comment by dragon731012** [comment]
Join my server for free links https://discord.gg/Vd5sJVqVzH
