### ISSUE TITLE
Use  YouTube apps all video ads don't show the skip button, which results in having to watch all ads!

### ISSUE THREAD

**Issue by zptqghsw** [dragon731012/DM-Unbl0cker#18]
Use  YouTube apps all video ads don't show the skip button, which results in having to watch all ads!

**Comment by dragon731012** [comment]
Are you using the recent version of DM Unbl0cker?

**Comment by zptqghsw** [comment]
Yes

**Comment by zptqghsw** [comment]
> Are you using the recent version of DM Unbl0cker?

The new version looks amazing, but still can't skip the commercials. Is there a fix planned?

**Comment by dragon731012** [comment]
I tested it, and it is working for me. Anyone else have this problem?

**Comment by zptqghsw** [comment]
It's supposed to be a browser compatibility issue. I tried to switch to Chrome and it worked fine. I had problems using Microsoft Edge.
