### ISSUE TITLE
Access to fetch at 'https://bare-server-vjra.onrender.com/v1/' from origin 'https://pp.hohoo.fun' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

### ISSUE THREAD

**Issue by zptqghsw** [dragon731012/DM-Unbl0cker#20]
Access to fetch at 'https://bare-server-vjra.onrender.com/v1/' from origin 'https://pp.hohoo.fun/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
What can I do if this error is reported in the browser?

**Comment by dragon731012** [comment]
What browser and what blocking extension

**Comment by zptqghsw** [comment]
Chrome，CORS policy, that is, the browser's security policy is the same source policy. I tried to unify the two domain names, and the problem was solved.
