### ISSUE TITLE
How do I deploy this project to nginx? I tried to clone the project to a VM and load it using nginx, and I found a lot of errors.

### ISSUE THREAD

**Issue by zptqghsw** [dragon731012/DM-Unbl0cker#21]
How do I deploy this project to nginx? I tried to clone the project to a VM and load it using nginx, and I found a lot of errors.

**Comment by dragon731012** [comment]
It is easier to just deploy it on a free hosting service, like https://netlify.com or https://vercel.com, and they both have a free plan of 100 gb of bandwidth a month, including free domains.
