### ISSUE TITLE
The Chrome console continuously prints errors such as bg.js:69 Uncaught TypeError: Cannot read properties of null (reading' appendChild') at bg.js:69:49. The number of errors may reach thousands

### ISSUE THREAD

**Issue by zptqghsw** [dragon731012/DM-Unbl0cker#22]
The Chrome console continuously prints errors such as bg.js:69 Uncaught TypeError: Cannot read properties of null (reading' appendChild') at bg.js:69:49. The number of errors may reach thousands

**Comment by dragon731012** [comment]
Ok, I’ll fix that, thank you

**Comment by dragon731012** [comment]
Fixed it, thank you for bringing it to my attention.
