### ISSUE TITLE
typeerror: failed to fetch

### ISSUE THREAD

**Issue by jack9192** [dragon731012/DM-Unbl0cker#27]
Whenever I try to open a game it says type error: failed to fetch, and the proxy isn't working. I have tried all of the troubleshooting methods, and they did not help.

**Comment by WithermaskSchool** [comment]
just host the bare server (pls give me provider rrender banned it :(

**Comment by jack9192** [comment]
Netlify

**Comment by dragon731012** [comment]
Cyclic
