### ISSUE TITLE
make settings dark mode & have adjustable dark mode settings

### ISSUE THREAD

**Issue by 22yeetz22** [dragon731012/DM-Unbl0cker#4]
also make the settings more understandable

add a back button

ik I'm spamming you
I'm sorry

**Comment by dragon731012** [comment]
Idk about dark mode, but I can add a back button.

**Comment by 22yeetz22** [comment]
the entire site is already dark mode, just make the settings dark mode

**Comment by dragon731012** [comment]
What’s the point if already dark mode

**Comment by dragon731012** [comment]
Added back button in settings
