### ISSUE TITLE
Genuine suggestion 

### ISSUE THREAD

**Issue by Tacogamerman** [dragon731012/DM-Unbl0cker#9]
Don’t take this as hate, this is a real suggestion. The ui is just ugly. The proxy itself is great, and many things you added are great, but the ui just isn’t good. One of the things I suggest is to trash the gif background (since it’s slow, laggy, and clearly looped), and replace it with some css animations. Another thing I suggest is to trash the cursor with the fire effect, and instead go for a cleaner look, similar to void. The cursor you are currently using just seems… cringe. I also think you should change the buttons in the game section to look more modern. Also you should make the cursor a pointer while on the search bar. 
My last suggestion is to make the discord icon less weirdly stretched, and more accurate. 
Anyways those were my suggestions for dm unblocker, I hope you use a few.

**Comment by Tacogamerman** [comment]
Lemme suggest stuff

**Comment by Tacogamerman** [comment]
Can’t take suggestions 💀

**Comment by Tacogamerman** [comment]
@dragon731012 You really gotta learn to allow valid criticism and feedback, cus right now, you acting like the Chinese government with your repos.

**Comment by Tacogamerman** [comment]
I like the unblocker, but the fact that you don’t take any feedback whatsoever with it is kinda cringe ngl.

**Comment by Tacogamerman** [comment]
I genuinely think that the few things that I suggested are what are slowing this unblocker down.

**Comment by Tacogamerman** [comment]
And honestly, bringing up how I messed up in a conversation where I’m trying to help you is kind of childish and stupid.

**Comment by Tacogamerman** [comment]
@dragon731012 Anyways if you don’t like the suggestions, that’s fine. But you shouldn’t mention how I made the same mistakes as you when I’m trying to help you, because that makes you seem like a crying baby refusing to take any help.

**Comment by Tacogamerman** [comment]
@dragon731012 Like bruh, bringing up something I made SPECIFICALLY to be more original, and to stop the beef between out servers because of how I copied the corrosion version of dm unblocker is extremely childish, and honestly, you need to just allow people to try t8 help out.

**Comment by dragon731012** [comment]
Ok, I added something in settings to turn off cursor and changed bg.

**Comment by Tacogamerman** [comment]
Ok, thanks for taking the feedback. Also sorry for writing a 16 paragraph essay lmao
